### ISSUE TITLE
Demonstrate using APRIL tags and LiDAR to navigate

### ISSUE THREAD

**Issue by billmania** [billmania/roboquest_addons#7]
Implement a ROS node which can be added as a User Node to a running Roboquest system. Connect the RPLiDAR sensor and use the existing Roboquest mast camera.

Accept, from the student, an ordered list of APRIL tag IDs.

This new User Node will then consume from the april_tag topic and publish to the cmd_vel topic, to move the robot autonomously to each APRIL tag in the list. The robot will stop in front of the last tag in the list.

If the LiDAR detects an obstacle in its path, it will adjust its path until it can again travel directly toward the tag or determines there is no path. The next tag in the list must always be visible, but not always directly reachable, from the robot's current position.

**Comment by billmania** [comment]
The message from the apriltag node, when an APRIL tag is detected, is:
```
header:
  stamp:
    sec: 1736196833
    nanosec: 138613013
  frame_id: camera
detections:
- family: tag36h11
  id: 586
  hamming: 0
  goodness: 0.0
  decision_margin: 138.93585205078125
  centre:
    x: 420.4451942718574
    y: 121.43241199123094
  corners:
  - x: 412.0328369140625
    y: 129.83345031738284
  - x: 429.9315185546875
    y: 129.76699829101562
  - x: 429.45736694335943
    y: 112.43236541748045
  - x: 411.8880310058594
    y: 113.91417694091798
  homography:
  - -9.2122893347792
  - -3.4409869372937028
  - 420.4451942718574
  - -5.609111961927725
  - 7.261263075220227
  - 121.43241199123094
  - -0.04295962966451276
  - -0.008536014640259954
  - 1.0
```

and when no tag is detected:

```
header:
  stamp:
    sec: 1736196939
    nanosec: 598086013
  frame_id: camera
detections: []
```

Transforms are published like:

```
transforms:                                                                                         
- header:                                                                                           
    stamp:                                                                                          
      sec: 1736206563                                                                               
      nanosec: 826205349                                                                            
    frame_id: camera                                                                                
  child_frame_id: six                                                                               
  transform:                                                                                        
    translation:                                                                                    
      x: 0.0                                                                                        
      y: 0.0                                                                                        
      z: 0.0                                                                                        
    rotation:                                                                                       
      x: 0.0                                                                                        
      y: 0.0                                                                                        
      z: 0.0                                                                                        
      w: 1.0  
```

**Comment by billmania** [comment]
Generate a PDF image of a camera calibration checkerboard with [calib.io Pattern Generator](https://calib.io/pages/camera-calibration-pattern-generator)

**Comment by billmania** [comment]
See [apriltag_ros wiki page](https://wiki.ros.org/apriltag_ros) for the list of parameters. Specifically, see:

- publish_tf
- camera_frame

**Comment by billmania** [comment]
When the apriltag_ros node detects a configured APRIL tag, it publishes messages to /tf like the following. NB The units of the translation vector are NOT meters. It's not yet known whether that's from a calibration problem.
```
---
transforms:
- header:
    stamp:
      sec: 1741017247
      nanosec: 588421966
    frame_id: camera
  child_frame_id: three
  transform:
    translation:
      x: -0.09898467871912503
      y: 0.24757578657797238
      z: 4.7875047161150786
    rotation:
      x: -0.9896651309958929
      y: -0.017321343968546114
      z: -0.03906365014649639
      w: 0.1368829089815001
---
transforms:
- header:
    stamp:
      sec: 1741017247
      nanosec: 620389966
    frame_id: camera
  child_frame_id: three
  transform:
    translation:
      x: -0.09888039876294519
      y: 0.2474343915432532
      z: 4.783722634230373
    rotation:
      x: -0.9894874576775022
      y: -0.017557024763264786
      z: -0.0393001362593627
      w: 0.13806455472122747
```
